// <auto-generated />
#nullable enable

namespace GostGen.DTO;

using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using YamlDotNet.Serialization;

/// <summary>
/// GOST (https://github.com/go-gost/gost) configuration serialization structures.
/// </summary>
[ExcludeFromCodeCoverage]
internal record GostConfig
{
    /// <summary>
    /// The configuration environment variable name
    /// </summary>
    internal const string ConfigFile = "data/gost.yaml";

    [YamlMember(Alias = "log")]
    public LogConfig? Log { get; set; }

    [YamlMember(Alias = "metrics")]
    public MetricsConfig? Metrics { get; set; }

    [YamlMember(Alias = "authers")]
    public List<AutherConfig>? Authers { get; set; }

    [YamlMember(Alias = "bypasses")]
    public List<BypassConfig>? Bypasses { get; set; }

    [YamlMember(Alias = "services")]
    public List<ServiceConfig>? Services { get; set; }

    [YamlMember(Alias = "chains")]
    public List<ChainConfig>? Chains { get; set; }

    //[YamlMember(Alias = "hops")]
    //public List<HopConfig> Hops? { get; set; }

    //[YamlMember(Alias = "admissions")]
    //public List<AdmissionConfig>? Admissions { get; set; }

    //[YamlMember(Alias = "resolvers")]
    //public List<ResolverConfig>? Resolvers { get; set; }

    //[YamlMember(Alias = "hosts")]
    //public List<HostsConfig>? Hosts { get; set; }

    //[YamlMember(Alias = "ingresses")]
    //public List<IngressConfig>? Ingresses { get; set; }

    //[YamlMember(Alias = "routers")]
    //public List<RouterConfig>? Routers { get; set; }

    //[YamlMember(Alias = "sds")]
    //public List<SDConfig>? SDs { get; set; }

    //[YamlMember(Alias = "recorders")]
    //public List<RecorderConfig>? Recorders { get; set; }

    //[YamlMember(Alias = "limiters")]
    //public List<LimiterConfig>? Limiters { get; set; }

    //[YamlMember(Alias = "climiters")]
    //public List<LimiterConfig>? CLimiters { get; set; }

    //[YamlMember(Alias = "rlimiters")]
    //public List<LimiterConfig>? RLimiters { get; set; }

    //[YamlMember(Alias = "observers")]
    //public List<ObserverConfig>? Observers { get; set; }

    //[YamlMember(Alias = "loggers")]
    //public List<LoggerConfig>? Loggers { get; set; }

    //[YamlMember(Alias = "tls")]
    //public TLSConfig? TLS { get; set; }

    //[YamlMember(Alias = "profiling")]
    //public ProfilingConfig? Profiling { get; set; }

    //[YamlMember(Alias = "api")]
    //public ApiConfig? API { get; set; }

    /// <summary>
    /// Loads the config from the given text.
    /// </summary>
    /// <param name="text">The yaml.</param>
    internal static GostConfig LoadYaml(string text)
    {
        return new DeserializerBuilder()
            .IgnoreUnmatchedProperties()
            .Build()
            .Deserialize<GostConfig>(text);
    }

    /// <summary>
    /// Converts the instance into a yaml formatted text.
    /// </summary>
    /// <param name="config">The configuration.</param>
    internal static string ToYaml(GostConfig config)
    {
        return new SerializerBuilder()
            .ConfigureDefaultValuesHandling(DefaultValuesHandling.OmitNull)
            .DisableAliases()
            .Build()
            .Serialize(config);
    }
}

[ExcludeFromCodeCoverage]
internal record LogConfig
{
    [YamlMember(Alias = "level")]
    public string? Level { get; set; }

    [YamlMember(Alias = "output")]
    public string? Output { get; set; }

    [YamlMember(Alias = "format")]
    public string? Format { get; set; }

    [YamlMember(Alias = "rotation")]
    public LogRotationConfig? Rotation { get; set; }
}

[ExcludeFromCodeCoverage]
internal record LogRotationConfig
{
    [YamlMember(Alias = "maxSize")]
    public int? MaxSize { get; set; }

    [YamlMember(Alias = "maxAge")]
    public int? MaxAge { get; set; }

    [YamlMember(Alias = "maxBackups")]
    public int? MaxBackups { get; set; }

    [YamlMember(Alias = "localTime")]
    public bool? LocalTime { get; set; }

    [YamlMember(Alias = "compress")]
    public bool? Compress { get; set; }
}

[ExcludeFromCodeCoverage]
internal record LoggerConfig
{
    [YamlMember(Alias = "name")]
    public string? Name { get; set; }

    [YamlMember(Alias = "log")]
    public LogConfig? Log { get; set; }
}

[ExcludeFromCodeCoverage]
internal record ProfilingConfig
{
    [YamlMember(Alias = "addr")]
    public string? Addr { get; set; }
}

[ExcludeFromCodeCoverage]
internal record ApiConfig
{
    [YamlMember(Alias = "addr")]
    public string? Addr { get; set; }

    [YamlMember(Alias = "pathPrefix")]
    public string? PathPrefix { get; set; }

    [YamlMember(Alias = "accesslog")]
    public bool? AccessLog { get; set; }

    [YamlMember(Alias = "auth")]
    public AuthConfig? Auth { get; set; }

    [YamlMember(Alias = "auther")]
    public string? Auther { get; set; }
}

[ExcludeFromCodeCoverage]
internal record MetricsConfig
{
    [YamlMember(Alias = "addr")]
    public string? Addr { get; set; }

    [YamlMember(Alias = "path")]
    public string? Path { get; set; }

    [YamlMember(Alias = "auth")]
    public AuthConfig? Auth { get; set; }

    [YamlMember(Alias = "auther")]
    public string? Auther { get; set; }
}

[ExcludeFromCodeCoverage]
internal record TLSConfig
{
    [YamlMember(Alias = "certFile")]
    public string? CertFile { get; set; }

    [YamlMember(Alias = "keyFile")]
    public string? KeyFile { get; set; }

    [YamlMember(Alias = "caFile")]
    public string? CAFile { get; set; }

    [YamlMember(Alias = "secure")]
    public bool? Secure { get; set; }

    [YamlMember(Alias = "serverName")]
    public string? ServerName { get; set; }

    [YamlMember(Alias = "options")]
    public TLSOptions? Options { get; set; }

    [YamlMember(Alias = "validity")]
    public string? Validity { get; set; }

    [YamlMember(Alias = "commonName")]
    public string? CommonName { get; set; }

    [YamlMember(Alias = "organization")]
    public string? Organization { get; set; }
}

[ExcludeFromCodeCoverage]
internal record TLSOptions
{
    [YamlMember(Alias = "minVersion")]
    public string? MinVersion { get; set; }

    [YamlMember(Alias = "maxVersion")]
    public string? MaxVersion { get; set; }

    [YamlMember(Alias = "cipherSuites")]
    public List<string>? CipherSuites { get; set; }

    [YamlMember(Alias = "alpn")]
    public List<string>? ALPN { get; set; }
}

[ExcludeFromCodeCoverage]
internal record PluginConfig
{
    [YamlMember(Alias = "type")]
    public string? Type { get; set; }

    [YamlMember(Alias = "addr")]
    public string? Addr { get; set; }

    [YamlMember(Alias = "tls")]
    public TLSConfig? TLS { get; set; }

    [YamlMember(Alias = "timeout")]
    public string? Timeout { get; set; }

    [YamlMember(Alias = "token")]
    public string? Token { get; set; }
}

[ExcludeFromCodeCoverage]
internal record AutherConfig
{
    [YamlMember(Alias = "name")]
    public string? Name { get; set; }

    [YamlMember(Alias = "auths")]
    public List<AuthConfig>? Auths { get; set; }

    [YamlMember(Alias = "reload")]
    public string? Reload { get; set; }

    [YamlMember(Alias = "file")]
    public FileLoader? File { get; set; }

    [YamlMember(Alias = "redis")]
    public RedisLoader? Redis { get; set; }

    [YamlMember(Alias = "http")]
    public HTTPLoader? HTTP { get; set; }

    [YamlMember(Alias = "plugin")]
    public PluginConfig? Plugin { get; set; }
}

[ExcludeFromCodeCoverage]
internal record AuthConfig
{
    [YamlMember(Alias = "username")]
    public string? Username { get; set; }

    [YamlMember(Alias = "password")]
    public string? Password { get; set; }

    [YamlMember(Alias = "file")]
    public string? File { get; set; }
}

[ExcludeFromCodeCoverage]
internal record SelectorConfig
{
    [YamlMember(Alias = "strategy")]
    public SelectorStrategy? Strategy { get; set; }

    [YamlMember(Alias = "maxFails")]
    public int? MaxFails { get; set; }

    [YamlMember(Alias = "failTimeout")]
    public string? FailTimeout { get; set; }
}

internal enum SelectorStrategy
{
    /// <summary>
    /// Round-robin
    /// </summary>
    round,

    /// <summary>
    /// Random
    /// </summary>
    rand,

    /// <summary>
    /// top-down fifo
    /// </summary>
    fifo,

    /// <summary>
    /// Based on a specific hash value (client IP or destination address)
    /// </summary>
    hash,
}

[ExcludeFromCodeCoverage]
internal record AdmissionConfig
{
    [YamlMember(Alias = "name")]
    public string? Name { get; set; }

    [YamlMember(Alias = "reverse")]
    public bool? Reverse { get; set; }

    [YamlMember(Alias = "whitelist")]
    public bool? Whitelist { get; set; }

    [YamlMember(Alias = "matchers")]
    public List<string>? Matchers { get; set; }

    [YamlMember(Alias = "reload")]
    public string? Reload { get; set; }

    [YamlMember(Alias = "file")]
    public FileLoader? File { get; set; }

    [YamlMember(Alias = "redis")]
    public RedisLoader? Redis { get; set; }

    [YamlMember(Alias = "http")]
    public HTTPLoader? HTTP { get; set; }

    [YamlMember(Alias = "plugin")]
    public PluginConfig? Plugin { get; set; }
}

[ExcludeFromCodeCoverage]
internal record BypassConfig
{
    [YamlMember(Alias = "name")]
    public string? Name { get; set; }

    [YamlMember(Alias = "reverse")]
    public bool? Reverse { get; set; }

    [YamlMember(Alias = "whitelist")]
    public bool? Whitelist { get; set; }

    [YamlMember(Alias = "matchers")]
    public List<string>? Matchers { get; set; }

    [YamlMember(Alias = "reload")]
    public string? Reload { get; set; }

    [YamlMember(Alias = "file")]
    public FileLoader? File { get; set; }

    [YamlMember(Alias = "redis")]
    public RedisLoader? Redis { get; set; }

    [YamlMember(Alias = "http")]
    public HTTPLoader? HTTP { get; set; }

    [YamlMember(Alias = "plugin")]
    public PluginConfig? Plugin { get; set; }
}

[ExcludeFromCodeCoverage]
internal record FileLoader
{
    [YamlMember(Alias = "path")]
    public string? Path { get; set; }
}

[ExcludeFromCodeCoverage]
internal record RedisLoader
{
    [YamlMember(Alias = "addr")]
    public string? Addr { get; set; }

    [YamlMember(Alias = "db")]
    public int? DB { get; set; }

    [YamlMember(Alias = "username")]
    public string? Username { get; set; }

    [YamlMember(Alias = "password")]
    public string? Password { get; set; }

    [YamlMember(Alias = "key")]
    public string? Key { get; set; }

    [YamlMember(Alias = "type")]
    public string? Type { get; set; }
}

[ExcludeFromCodeCoverage]
internal record HTTPLoader
{
    [YamlMember(Alias = "url")]
    public string? URL { get; set; }

    [YamlMember(Alias = "timeout")]
    public string? Timeout { get; set; }
}

[ExcludeFromCodeCoverage]
internal record NameserverConfig
{
    [YamlMember(Alias = "addr")]
    public string? Addr { get; set; }

    [YamlMember(Alias = "chain")]
    public string? Chain { get; set; }

    [YamlMember(Alias = "prefer")]
    public string? Prefer { get; set; }

    [YamlMember(Alias = "clientIP")]
    public string? ClientIP { get; set; }

    [YamlMember(Alias = "hostname")]
    public string? Hostname { get; set; }

    [YamlMember(Alias = "ttl")]
    public string? TTL { get; set; }

    [YamlMember(Alias = "timeout")]
    public string? Timeout { get; set; }

    [YamlMember(Alias = "async")]
    public bool? Async { get; set; }

    [YamlMember(Alias = "only")]
    public string? Only { get; set; }
}

[ExcludeFromCodeCoverage]
internal record ResolverConfig
{
    [YamlMember(Alias = "name")]
    public string? Name { get; set; }

    [YamlMember(Alias = "nameservers")]
    public List<NameserverConfig>? Nameservers { get; set; }

    [YamlMember(Alias = "plugin")]
    public PluginConfig? Plugin { get; set; }
}

[ExcludeFromCodeCoverage]
internal record HostMappingConfig
{
    [YamlMember(Alias = "ip")]
    public string? IP { get; set; }

    [YamlMember(Alias = "hostname")]
    public string? Hostname { get; set; }

    [YamlMember(Alias = "aliases")]
    public List<string>? Aliases { get; set; }
}

[ExcludeFromCodeCoverage]
internal record HostsConfig
{
    [YamlMember(Alias = "name")]
    public string? Name { get; set; }

    [YamlMember(Alias = "mappings")]
    public List<HostMappingConfig>? Mappings { get; set; }

    [YamlMember(Alias = "reload")]
    public string? Reload { get; set; }

    [YamlMember(Alias = "file")]
    public FileLoader? File { get; set; }

    [YamlMember(Alias = "redis")]
    public RedisLoader? Redis { get; set; }

    [YamlMember(Alias = "http")]
    public HTTPLoader? HTTP { get; set; }

    [YamlMember(Alias = "plugin")]
    public PluginConfig? Plugin { get; set; }
}

[ExcludeFromCodeCoverage]
internal record IngressRuleConfig
{
    [YamlMember(Alias = "hostname")]
    public string? Hostname { get; set; }

    [YamlMember(Alias = "endpoint")]
    public string? Endpoint { get; set; }
}

[ExcludeFromCodeCoverage]
internal record IngressConfig
{
    [YamlMember(Alias = "name")]
    public string? Name { get; set; }

    [YamlMember(Alias = "rules")]
    public List<IngressRuleConfig>? Rules { get; set; }

    [YamlMember(Alias = "reload")]
    public string? Reload { get; set; }

    [YamlMember(Alias = "file")]
    public FileLoader? File { get; set; }

    [YamlMember(Alias = "redis")]
    public RedisLoader? Redis { get; set; }

    [YamlMember(Alias = "http")]
    public HTTPLoader? HTTP { get; set; }

    [YamlMember(Alias = "plugin")]
    public PluginConfig? Plugin { get; set; }
}

[ExcludeFromCodeCoverage]
internal record SDConfig
{
    [YamlMember(Alias = "name")]
    public string? Name { get; set; }

    [YamlMember(Alias = "plugin")]
    public PluginConfig? Plugin { get; set; }
}

[ExcludeFromCodeCoverage]
internal record RouterRouteConfig
{
    [YamlMember(Alias = "net")]
    public string? Net { get; set; }

    [YamlMember(Alias = "dst")]
    public string? Dst { get; set; }

    [YamlMember(Alias = "gateway")]
    public string? Gateway { get; set; }
}

[ExcludeFromCodeCoverage]
internal record RouterConfig
{
    [YamlMember(Alias = "name")]
    public string? Name { get; set; }

    [YamlMember(Alias = "routes")]
    public List<RouterRouteConfig>? Routes { get; set; }

    [YamlMember(Alias = "reload")]
    public string? Reload { get; set; }

    [YamlMember(Alias = "file")]
    public FileLoader? File { get; set; }

    [YamlMember(Alias = "redis")]
    public RedisLoader? Redis { get; set; }

    [YamlMember(Alias = "http")]
    public HTTPLoader? HTTP { get; set; }

    [YamlMember(Alias = "plugin")]
    public PluginConfig? Plugin { get; set; }
}

[ExcludeFromCodeCoverage]
internal record RecorderConfig
{
    [YamlMember(Alias = "name")]
    public string? Name { get; set; }

    [YamlMember(Alias = "file")]
    public FileRecorder? File { get; set; }

    [YamlMember(Alias = "tcp")]
    public TCPRecorder? TCP { get; set; }

    [YamlMember(Alias = "http")]
    public HTTPRecorder? HTTP { get; set; }

    [YamlMember(Alias = "redis")]
    public RedisRecorder? Redis { get; set; }

    [YamlMember(Alias = "plugin")]
    public PluginConfig? Plugin { get; set; }
}

[ExcludeFromCodeCoverage]
internal record FileRecorder
{
    [YamlMember(Alias = "path")]
    public string? Path { get; set; }

    [YamlMember(Alias = "sep")]
    public string? Sep { get; set; }

    [YamlMember(Alias = "rotation")]
    public LogRotationConfig? Rotation { get; set; }
}

[ExcludeFromCodeCoverage]
internal record TCPRecorder
{
    [YamlMember(Alias = "addr")]
    public string? Addr { get; set; }

    [YamlMember(Alias = "timeout")]
    public string? Timeout { get; set; }
}

[ExcludeFromCodeCoverage]
internal record HTTPRecorder
{
    [YamlMember(Alias = "url")]
    public string? URL { get; set; }

    [YamlMember(Alias = "timeout")]
    public string? Timeout { get; set; }

    [YamlMember(Alias = "header")]
    public Dictionary<string, string>? Header { get; set; }
}

[ExcludeFromCodeCoverage]
internal record RedisRecorder
{
    [YamlMember(Alias = "addr")]
    public string? Addr { get; set; }

    [YamlMember(Alias = "db")]
    public int? DB { get; set; }

    [YamlMember(Alias = "username")]
    public string? Username { get; set; }

    [YamlMember(Alias = "password")]
    public string? Password { get; set; }

    [YamlMember(Alias = "key")]
    public string? Key { get; set; }

    [YamlMember(Alias = "type")]
    public string? Type { get; set; }
}

[ExcludeFromCodeCoverage]
internal record RecorderObject
{
    [YamlMember(Alias = "name")]
    public string? Name { get; set; }

    [YamlMember(Alias = "record")]
    public string? Record { get; set; }

    [YamlMember(Alias = "metadata")]
    public Dictionary<string, object?>? Metadata { get; set; }
}

[ExcludeFromCodeCoverage]
internal record LimiterConfig
{
    [YamlMember(Alias = "name")]
    public string? Name { get; set; }

    [YamlMember(Alias = "limits")]
    public List<string>? Limits { get; set; }

    [YamlMember(Alias = "reload")]
    public string? Reload { get; set; }

    [YamlMember(Alias = "file")]
    public FileLoader? File { get; set; }

    [YamlMember(Alias = "redis")]
    public RedisLoader? Redis { get; set; }

    [YamlMember(Alias = "http")]
    public HTTPLoader? HTTP { get; set; }

    [YamlMember(Alias = "plugin")]
    public PluginConfig? Plugin { get; set; }
}

[ExcludeFromCodeCoverage]
internal record ObserverConfig
{
    [YamlMember(Alias = "name")]
    public string? Name { get; set; }

    [YamlMember(Alias = "plugin")]
    public PluginConfig? Plugin { get; set; }
}

[ExcludeFromCodeCoverage]
internal record ListenerConfig
{
    [YamlMember(Alias = "type")]
    public string? Type { get; set; }

    [YamlMember(Alias = "auther")]
    public string? Auther { get; set; }

    [YamlMember(Alias = "authers")]
    public List<string>? Authers { get; set; }

    [YamlMember(Alias = "auth")]
    public AuthConfig? Auth { get; set; }

    [YamlMember(Alias = "chain")]
    public string? Chain { get; set; }

    [YamlMember(Alias = "chainGroup")]
    public ChainGroupConfig? ChainGroup { get; set; }

    [YamlMember(Alias = "tls")]
    public TLSConfig? TLS { get; set; }

    [YamlMember(Alias = "metadata")]
    public Dictionary<string, object?>? Metadata { get; set; }
}

[ExcludeFromCodeCoverage]
internal record HandlerConfig
{
    [YamlMember(Alias = "type")]
    public string? Type { get; set; }

    [YamlMember(Alias = "retries")]
    public int? Retries { get; set; }

    [YamlMember(Alias = "auther")]
    public string? Auther { get; set; }

    [YamlMember(Alias = "authers")]
    public List<string>? Authers { get; set; }

    [YamlMember(Alias = "auth")]
    public AuthConfig? Auth { get; set; }

    [YamlMember(Alias = "chain")]
    public string? Chain { get; set; }

    [YamlMember(Alias = "chainGroup")]
    public ChainGroupConfig? ChainGroup { get; set; }

    [YamlMember(Alias = "tls")]
    public TLSConfig? TLS { get; set; }

    [YamlMember(Alias = "limiter")]
    public string? Limiter { get; set; }

    [YamlMember(Alias = "observer")]
    public string? Observer { get; set; }

    [YamlMember(Alias = "metadata")]
    public Dictionary<string, object?>? Metadata { get; set; }
}

[ExcludeFromCodeCoverage]
internal record ForwarderConfig
{
    [YamlMember(Alias = "name")]
    public string? Name { get; set; }

    [YamlMember(Alias = "hop")]
    public string? Hop { get; set; }

    [YamlMember(Alias = "selector")]
    public SelectorConfig? Selector { get; set; }

    [YamlMember(Alias = "nodes")]
    public List<ForwardNodeConfig>? Nodes { get; set; }
}

[ExcludeFromCodeCoverage]
internal record ForwardNodeConfig
{
    [YamlMember(Alias = "name")]
    public string? Name { get; set; }

    [YamlMember(Alias = "addr")]
    public string? Addr { get; set; }

    [YamlMember(Alias = "network")]
    public string? Network { get; set; }

    [YamlMember(Alias = "bypass")]
    public string? Bypass { get; set; }

    [YamlMember(Alias = "bypasses")]
    public List<string>? Bypasses { get; set; }

    [YamlMember(Alias = "protocol")]
    public string? Protocol { get; set; }

    [YamlMember(Alias = "host")]
    public string? Host { get; set; }

    [YamlMember(Alias = "path")]
    public string? Path { get; set; }

    [YamlMember(Alias = "filter")]
    public NodeFilterConfig? Filter { get; set; }

    [YamlMember(Alias = "matcher")]
    public NodeMatcherConfig? Matcher { get; set; }

    [YamlMember(Alias = "auth")]
    public AuthConfig? Auth { get; set; }

    [YamlMember(Alias = "http")]
    public HTTPNodeConfig? HTTP { get; set; }

    [YamlMember(Alias = "tls")]
    public TLSNodeConfig? TLS { get; set; }

    [YamlMember(Alias = "metadata")]
    public Dictionary<string, object?>? Metadata { get; set; }
}

[ExcludeFromCodeCoverage]
internal record NodeFilterConfig
{
    [YamlMember(Alias = "host")]
    public string? Host { get; set; }

    [YamlMember(Alias = "protocol")]
    public string? Protocol { get; set; }

    [YamlMember(Alias = "path")]
    public string? Path { get; set; }
}

[ExcludeFromCodeCoverage]
internal record NodeMatcherConfig
{
    [YamlMember(Alias = "rule")]
    public string? Rule { get; set; }

    [YamlMember(Alias = "priority")]
    public int? Priority { get; set; }
}

[ExcludeFromCodeCoverage]
internal record HTTPNodeConfig
{
    [YamlMember(Alias = "host")]
    public string? Host { get; set; }

    [YamlMember(Alias = "header")]
    public Dictionary<string, string>? Header { get; set; }

    [YamlMember(Alias = "requestHeader")]
    public Dictionary<string, string>? RequestHeader { get; set; }

    [YamlMember(Alias = "responseHeader")]
    public Dictionary<string, string>? ResponseHeader { get; set; }

    [YamlMember(Alias = "auth")]
    public AuthConfig? Auth { get; set; }
}

[ExcludeFromCodeCoverage]
internal record TLSNodeConfig
{
    [YamlMember(Alias = "serverName")]
    public string? ServerName { get; set; }

    [YamlMember(Alias = "secure")]
    public bool Secure { get; set; }

    [YamlMember(Alias = "options")]
    public TLSOptions? Options { get; set; }
}

[ExcludeFromCodeCoverage]
internal record DialerConfig
{
    [YamlMember(Alias = "type")]
    public string? Type { get; set; }

    [YamlMember(Alias = "auth")]
    public AuthConfig? Auth { get; set; }

    [YamlMember(Alias = "tls")]
    public TLSConfig? TLS { get; set; }

    [YamlMember(Alias = "metadata")]
    public Dictionary<string, object?>? Metadata { get; set; }
}

[ExcludeFromCodeCoverage]
internal record ConnectorConfig
{
    [YamlMember(Alias = "type")]
    public string? Type { get; set; }

    [YamlMember(Alias = "auth")]
    public AuthConfig? Auth { get; set; }

    [YamlMember(Alias = "tls")]
    public TLSConfig? TLS { get; set; }

    [YamlMember(Alias = "metadata")]
    public Dictionary<string, object?>? Metadata { get; set; }
}

[ExcludeFromCodeCoverage]
internal record SockOptsConfig
{
    [YamlMember(Alias = "mark")]
    public int? Mark { get; set; }
}

[ExcludeFromCodeCoverage]
internal record ServiceConfig
{
    [YamlMember(Alias = "name")]
    public string? Name { get; set; }

    [YamlMember(Alias = "addr")]
    public string? Addr { get; set; }

    [YamlMember(Alias = "interface")]
    public string? Interface { get; set; }

    [YamlMember(Alias = "sockopts")]
    public SockOptsConfig? SockOpts { get; set; }

    [YamlMember(Alias = "admission")]
    public string? Admission { get; set; }

    [YamlMember(Alias = "admissions")]
    public List<string>? Admissions { get; set; }

    [YamlMember(Alias = "bypass")]
    public string? Bypass { get; set; }

    [YamlMember(Alias = "bypasses")]
    public List<string>? Bypasses { get; set; }

    [YamlMember(Alias = "resolver")]
    public string? Resolver { get; set; }

    [YamlMember(Alias = "hosts")]
    public string? Hosts { get; set; }

    [YamlMember(Alias = "limiter")]
    public string? Limiter { get; set; }

    [YamlMember(Alias = "climiter")]
    public string? CLimiter { get; set; }

    [YamlMember(Alias = "rlimiter")]
    public string? RLimiter { get; set; }

    [YamlMember(Alias = "logger")]
    public string? Logger { get; set; }

    [YamlMember(Alias = "loggers")]
    public List<string>? Loggers { get; set; }

    [YamlMember(Alias = "observer")]
    public string? Observer { get; set; }

    [YamlMember(Alias = "recorders")]
    public List<RecorderObject>? Recorders { get; set; }

    [YamlMember(Alias = "handler")]
    public HandlerConfig? Handler { get; set; }

    [YamlMember(Alias = "listener")]
    public ListenerConfig? Listener { get; set; }

    [YamlMember(Alias = "forwarder")]
    public ForwarderConfig? Forwarder { get; set; }

    [YamlMember(Alias = "metadata")]
    public Dictionary<string, object?>? Metadata { get; set; }

    [YamlMember(Alias = "status")]
    public ServiceStatus? Status { get; set; }
}

[ExcludeFromCodeCoverage]
internal record ServiceStatus
{
    [YamlMember(Alias = "createTime")]
    public long? CreateTime { get; set; }

    [YamlMember(Alias = "state")]
    public string? State { get; set; }

    [YamlMember(Alias = "events")]
    public List<ServiceEvent>? Events { get; set; }

    [YamlMember(Alias = "stats")]
    public ServiceStats? Stats { get; set; }
}

[ExcludeFromCodeCoverage]
internal record ServiceEvent
{
    [YamlMember(Alias = "time")]
    public long? Time { get; set; }

    [YamlMember(Alias = "msg")]
    public string? Msg { get; set; }
}

[ExcludeFromCodeCoverage]
internal record ServiceStats
{
    [YamlMember(Alias = "totalConns")]
    public ulong? TotalConns { get; set; }

    [YamlMember(Alias = "currentConns")]
    public ulong? CurrentConns { get; set; }

    [YamlMember(Alias = "totalErrs")]
    public ulong? TotalErrs { get; set; }

    [YamlMember(Alias = "inputBytes")]
    public ulong? InputBytes { get; set; }

    [YamlMember(Alias = "outputBytes")]
    public ulong? OutputBytes { get; set; }
}

[ExcludeFromCodeCoverage]
internal record ChainConfig
{
    [YamlMember(Alias = "name")]
    public string? Name { get; set; }

    [YamlMember(Alias = "hops")]
    public List<HopConfig>? Hops { get; set; }

    [YamlMember(Alias = "metadata")]
    public Dictionary<string, object?>? Metadata { get; set; }
}

[ExcludeFromCodeCoverage]
internal record ChainGroupConfig
{
    [YamlMember(Alias = "chains")]
    public List<string>? Chains { get; set; }

    [YamlMember(Alias = "selector")]
    public SelectorConfig? Selector { get; set; }
}

[ExcludeFromCodeCoverage]
internal record HopConfig
{
    [YamlMember(Alias = "name")]
    public string? Name { get; set; }

    [YamlMember(Alias = "interface")]
    public string? Interface { get; set; }

    [YamlMember(Alias = "sockopts")]
    public SockOptsConfig? SockOpts { get; set; }

    [YamlMember(Alias = "selector")]
    public SelectorConfig? Selector { get; set; }

    [YamlMember(Alias = "bypass")]
    public string? Bypass { get; set; }

    [YamlMember(Alias = "bypasses")]
    public List<string>? Bypasses { get; set; }

    [YamlMember(Alias = "resolver")]
    public string? Resolver { get; set; }

    [YamlMember(Alias = "hosts")]
    public string? Hosts { get; set; }

    [YamlMember(Alias = "nodes")]
    public List<NodeConfig>? Nodes { get; set; }

    [YamlMember(Alias = "reload")]
    public string? Reload { get; set; }

    [YamlMember(Alias = "file")]
    public FileLoader? File { get; set; }

    [YamlMember(Alias = "redis")]
    public RedisLoader? Redis { get; set; }

    [YamlMember(Alias = "http")]
    public HTTPLoader? HTTP { get; set; }

    [YamlMember(Alias = "plugin")]
    public PluginConfig? Plugin { get; set; }

    [YamlMember(Alias = "metadata")]
    public Dictionary<string, object?>? Metadata { get; set; }
}

[ExcludeFromCodeCoverage]
internal record NodeConfig
{
    [YamlMember(Alias = "name")]
    public string? Name { get; set; }

    [YamlMember(Alias = "bypass")]
    public string? Bypass { get; set; }

    [YamlMember(Alias = "addr")]
    public string? Addr { get; set; }

    [YamlMember(Alias = "network")]
    public string? Network { get; set; }

    [YamlMember(Alias = "bypasses")]
    public List<string>? Bypasses { get; set; }

    [YamlMember(Alias = "resolver")]
    public string? Resolver { get; set; }

    [YamlMember(Alias = "hosts")]
    public string? Hosts { get; set; }

    [YamlMember(Alias = "connector")]
    public ConnectorConfig? Connector { get; set; }

    [YamlMember(Alias = "dialer")]
    public DialerConfig? Dialer { get; set; }

    [YamlMember(Alias = "interface")]
    public string? Interface { get; set; }

    [YamlMember(Alias = "netns")]
    public string? Netns { get; set; }

    [YamlMember(Alias = "sockopts")]
    public SockOptsConfig? SockOpts { get; set; }

    [YamlMember(Alias = "filter")]
    public NodeFilterConfig? Filter { get; set; }

    [YamlMember(Alias = "matcher")]
    public NodeMatcherConfig? Matcher { get; set; }

    [YamlMember(Alias = "http")]
    public HTTPNodeConfig? HTTP { get; set; }

    [YamlMember(Alias = "tls")]
    public TLSNodeConfig? TLS { get; set; }

    [YamlMember(Alias = "metadata")]
    public Dictionary<string, object?>? Metadata { get; set; }
}