name: Update Upstream Dependencies

# Required Repo Setting!!! Settings → Actions → General → Workflow permissions [`Allow GitHub Actions to create and approve pull requests`]

on:
  schedule:
    - cron: '0 10 * * 5' # Every Friday at 10:00 UTC
  workflow_dispatch:

concurrency:
  group: update-upstream-deps
  cancel-in-progress: true

jobs:
  update:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    
    - name: Get Dependency Version Info
      id: versions
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        set -euo pipefail
        
        gost_current="$(sed -n -E 's/^ARG GOST_VERSION=//p' Dockerfile | head -n1)"
        echo "gost_current=$gost_current" >> "$GITHUB_OUTPUT"
        echo "::notice::[info] gost_current=$gost_current"
        gost_latest="$(gh release view --repo go-gost/gost --json tagName --jq '.tagName' | sed 's/^v//')"
        echo "gost_latest=$gost_latest" >> "$GITHUB_OUTPUT"
        echo "::notice::[info] gost_latest=$gost_latest"
        [[ "$gost_current" != "$gost_latest" ]] && gost_changed=true || gost_changed=false
        echo "gost_changed=$gost_changed" >> "$GITHUB_OUTPUT"
        echo "::notice::[info] gost_changed=$gost_changed"
        
        [[ "$gost_changed" == "true" ]] && update_available=true || update_available=false
        echo "update_available=$update_available" >> "$GITHUB_OUTPUT"
        echo "::notice::[info] update_available=$update_available"
    
    - name: Update Dependency Versions
      if: ${{ steps.versions.outputs.update_available == 'true' }}
      run: |
        set -euo pipefail
        
        sed -i -E 's/^(ARG GOST_VERSION=).*/\1${{ steps.versions.outputs.gost_latest }}/' Dockerfile
        sed -i -E 's/^(GOST_VERSION=).*/\1${{ steps.versions.outputs.gost_latest }}/' debug.sh
    
    - name: Create GitHub App token
      id: app-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ secrets.UPDATE_BOT_APP_ID }}
        private-key: ${{ secrets.UPDATE_BOT_PRIVATE_KEY }}
    
    - name: Create Pull Request
      if: ${{ steps.versions.outputs.update_available == 'true' }}
      uses: peter-evans/create-pull-request@v8
      with:
        token: ${{ steps.app-token.outputs.token }}
        branch: feature/UpstreamDependencyUpdate
        delete-branch: true
        title: "Update Upstream Dependencies"
        commit-message: "Update Upstream Dependencies"
        body: |
          Updated upstream dependency:
          - GOST: `${{ steps.versions.outputs.gost_current }}` to `${{ steps.versions.outputs.gost_latest }}`
